fix bug in Spi2CarbondataTypeMapper method, it will cause exception like
com.facebook.presto.spi.PrestoException: DECIMAL precision must be in range [1, 38]
         at com.facebook.presto.spi.type.DecimalType.validatePrecisionScale(DecimalType.java:94)
         at com.facebook.presto.spi.type.ShortDecimalType.<init>(ShortDecimalType.java:34)
         at com.facebook.presto.spi.type.DecimalType.createDecimalType(DecimalType.java:37)
         at org.apache.carbondata.presto.CarbondataRecordSetProvider.Spi2CarbondataTypeMapper(CarbondataRecordSetProvider.java:257)