[CARBONDATA-2117]Fixed Syncronization issue in CarbonEnv
Problem: When creating multiple session (100) session initialisation is failing with below error

java.lang.IllegalArgumentException: requirement failed: Config entry enable.unsafe.sort already registered!

Solution: Currently in CarbonEnv we are updating global configuration(shared) and location configuration in class level synchronized block. In case of multiple session class level lock will not work , need to add global level lock so only one thread will update the global configuration

This closes #1908