[CARBONDATA-3068] fixed cannot load data from hdfs files without hdfs prefix
sql:
LOAD DATA INPATH '/tmp/test.csv' INTO TABLE test OPTIONS('QUOTECHAR'='"','TIMESTAMPFORMAT'='yyyy/MM/dd HH:mm:ss');
error:
org.apache.carbondata.processing.exception.DataLoadingException: The input file does not exist: /tmp/test.csv (state=,code=0)
but the file "test.csv" is in hdfs path, and hadoop conf "core-site.xml" has the property:

fs.defaultFS
hdfs://master:9000

This closes #2891