[HOTFIX] Exclude filter doesn't work in presto carbon in cluster
problem1: Exclude filter fails in cluster for presto carbon with exception.

java.lang.NoClassDefFoundError: org/roaringbitmap/RoaringBitmap
        at org.apache.carbondata.core.scan.filter.FilterUtil.prepareExcludeFilterMembers(FilterUtil.java:826)
        at org.apache.carbondata.core.scan.filter.FilterUtil.getDimColumnFilterInfoAfterApplyingCBO(FilterUtil.java:776)
        at org.apache.carbondata.core.scan.filter.FilterUtil.getFilterListForAllValues(FilterUtil.java:884)

cause: RoaringBitmap jar is not added in the dependency, hence it is not present in the presto snapshot folder.
solution : include RoaringBitmap in dependency.

problem2: Local dictionary reset was not proper in vector for presto slice reader.
cause : For each batch local dictionary was resetting. Instead of the actual place reset.
solution : reset local dictionary when dictionary is set to null.

This closes #3060